### ISSUE TITLE
Create API documentation

### ISSUE THREAD

**Issue by philngo** [impactlab/oeem-energy-datastore#15]

**Comment by hunterowens** [comment]
What about [DRF Docs](https://github.com/ekonstantinidis/django-rest-framework-docs)

**Comment by philngo** [comment]
Looks promising! And very young. When I last looked for something like this (in October), this project didn't exist yet.

**Comment by hunterowens** [comment]
Yes. 

It is a port of an older project, but comes recommended from the [DRF core team](http://www.django-rest-framework.org/topics/documenting-your-api/).
